# Generated by Django 2.0.7 on 2018-07-18 11:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fapp', '0002_minibudget'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Budget',
            new_name='BudgetModel',
        ),
        migrations.RenameModel(
            old_name='MiniBudget',
            new_name='MiniBudgetModel',
        ),
    ]
