# Generated by Django 2.0.7 on 2018-09-09 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0003_auto_20180718_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='IncomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='MiniExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fapp.ExpenseModel')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.RemoveField(
            model_name='minibudgetmodel',
            name='budget',
        ),
        migrations.AlterModelOptions(
            name='budgetmodel',
            options={'ordering': ['date_created']},
        ),
        migrations.RemoveField(
            model_name='budgetmodel',
            name='amount',
        ),
        migrations.AddField(
            model_name='budgetmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetmodel',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='budgetmodel',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetmodel',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MiniBudgetModel',
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fapp.BudgetModel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fapp.BudgetModel'),
        ),
    ]
