# Generated by Django 2.0.7 on 2018-09-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0005_auto_20180909_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetmodel',
            options={'ordering': ['date_created']},
        ),
    ]
