# Generated by Django 2.0.7 on 2018-09-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0007_auto_20180924_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetmodel',
            name='total_expenses',
            field=models.IntegerField(default=0),
        ),
    ]
