# Generated by Django 2.0.7 on 2018-09-24 12:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0008_auto_20180924_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetmodel',
            name='total_income_currency',
        ),
        migrations.AlterField(
            model_name='budgetmodel',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='budgetmodel',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
