# Generated by Django 2.0.7 on 2018-09-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0009_auto_20180924_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetmodel',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='budgetmodel',
            name='total_income',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
