# Generated by Django 2.0.7 on 2018-10-02 13:11

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0010_auto_20180924_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetmodel',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='budgetmodel',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='budgetmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fapp.BudgetModel'),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='fapp.BudgetModel'),
        ),
        migrations.AlterField(
            model_name='miniexpensemodel',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miniexpenses', to='fapp.ExpenseModel'),
        ),
    ]
